title: Sunny Myungsun Kang
author: Yours truly
email: sunnybesunny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You found moi
# social links
twitter_username: sunnybesunny
github_username:  sunnybesunny

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
